BEGIN TRANSACTION;
DROP TABLE IF EXISTS "words";
CREATE TABLE IF NOT EXISTS "words" (
	"id"	INTEGER NOT NULL,
	"word"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "definitions";
CREATE TABLE IF NOT EXISTS "definitions" (
	"id"	INTEGER,
	"words_id"	INTEGER,
	"description"	TEXT NOT NULL UNIQUE,
	"example"	TEXT UNIQUE,
	FOREIGN KEY("words_id") REFERENCES "words"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
